s:730:"<strong>Stack trace: </strong> <ul style="text-align:left;"><li>line 494 of \lib\dml\moodle_database.php: dml_read_exception thrown</li><li>line 293 of \lib\dml\moodle_read_slave_trait.php: call to moodle_database-&gt;query_end()</li><li>line 1221 of \lib\dml\mysqli_native_moodle_database.php: call to mysqli_native_moodle_database-&gt;query_end()</li><li>line 2010 of \lib\dml\moodle_database.php: call to mysqli_native_moodle_database-&gt;get_recordset_sql()</li><li>line 398 of \message\classes\helper.php: call to moodle_database-&gt;record_exists_sql()</li><li>line 4633 of \lib\moodlelib.php: call to core_message\helper::legacy_messages_exist()</li><li>line 211 of \login\index.php: call to complete_user_login()</li></ul>";